[package]
name = "untabify"
description = "A tool to un-tabify files"
version = "0.1.0"
edition = "2021"
authors = ["Simon Curtis"]

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
glob = "0.3.1"
walkdir = "2.5.0"
